# Generated by Django 5.2.5 on 2025-08-14 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('domain', models.CharField(max_length=100, verbose_name='Домен')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время попытки входа')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Неудачно'), ('blocked', 'Заблокирован')], max_length=20, verbose_name='Статус входа')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('external_api_response', models.JSONField(blank=True, null=True, verbose_name='Ответ внешнего API')),
            ],
            options={
                'verbose_name': 'Аудит входа',
                'verbose_name_plural': 'Аудит входов',
                'db_table': 'login_audit',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['username', 'login_time'], name='login_audit_usernam_dc2b12_idx'), models.Index(fields=['ip_address', 'login_time'], name='login_audit_ip_addr_0d1c5c_idx'), models.Index(fields=['status', 'login_time'], name='login_audit_status_0d552e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('domain', models.CharField(max_length=100, verbose_name='Домен')),
                ('group_name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Группа пользователя',
                'verbose_name_plural': 'Группы пользователей',
                'db_table': 'user_groups',
                'indexes': [models.Index(fields=['username', 'domain'], name='user_groups_usernam_8a08cc_idx'), models.Index(fields=['group_name'], name='user_groups_group_n_f2906b_idx')],
                'unique_together': {('username', 'domain', 'group_name')},
            },
        ),
    ]
