# Generated by Django 5.2.5 on 2025-08-15 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Дата введения в действие')),
                ('finish_date', models.DateField(default='9999-12-31', verbose_name='дата окончания действия')),
                ('name_eng', models.CharField(blank=True, max_length=255, verbose_name='Название на английском языке')),
                ('description_eng', models.TextField(blank=True, verbose_name='Описание на английском языке')),
                ('name_bel', models.CharField(blank=True, max_length=255, verbose_name='Название на белорусском языке')),
                ('description_bel', models.TextField(blank=True, verbose_name='Описание на белорусском языке')),
                ('gko', models.CharField(blank=True, max_length=255, verbose_name='ГКО')),
                ('classifier', models.CharField(blank=True, max_length=255, verbose_name='классификатор')),
                ('id_status', models.IntegerField(choices=[(0, 'Не действующий'), (1, 'Действующий')], default=1, verbose_name='Статус')),
                ('id_type', models.IntegerField(choices=[(0, 'На основе классификатора'), (1, 'Локальный справочник')], default=0, verbose_name='Тип справочника')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Ответственная организация')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID справочника')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['name'],
            },
        ),
    ]
